import Head from "next/head";
import { Jost } from 'next/font/google';
import "../public/css/globals.css";

const font = Jost({
  weight: '300', // 700 for bold
  subsets: ['latin'],
});

export const viewport = {
    width: 'device-width',
    initialScale: 1,
    //maximumScale: 1,
    userScalable: true,
}

export const metadata = {
  title: "Noughts & Crosses | Huyton Web Services",
  description: "Generated by create next app",
  author: "Huyton Web Services",
  keywords: "Huyton, Web, Services",
  robots: "all"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={font.className}>{children}</body>
    </html>
  );
}
